// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXMO4Nqjy3HrcpxG2I2m9d1LKjAgEPcAo',
    appId: '1:1087764324748:web:03a19cdf0f5f6b17d9f6a9',
    messagingSenderId: '1087764324748',
    projectId: 'auth-tutorial-c6e06',
    authDomain: 'auth-tutorial-c6e06.firebaseapp.com',
    storageBucket: 'auth-tutorial-c6e06.appspot.com',
    measurementId: 'G-K2NKX0814P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYEwtnWxS3gucEOc1HfaYZzvKe4nR3X10',
    appId: '1:1087764324748:android:f5811d19138ff2a0d9f6a9',
    messagingSenderId: '1087764324748',
    projectId: 'auth-tutorial-c6e06',
    storageBucket: 'auth-tutorial-c6e06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2i0_-xr7eU67d-rMuEejagax87qTZXtg',
    appId: '1:1087764324748:ios:74016f9961cdf069d9f6a9',
    messagingSenderId: '1087764324748',
    projectId: 'auth-tutorial-c6e06',
    storageBucket: 'auth-tutorial-c6e06.appspot.com',
    iosBundleId: 'com.example.cardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2i0_-xr7eU67d-rMuEejagax87qTZXtg',
    appId: '1:1087764324748:ios:618c82bfc851872cd9f6a9',
    messagingSenderId: '1087764324748',
    projectId: 'auth-tutorial-c6e06',
    storageBucket: 'auth-tutorial-c6e06.appspot.com',
    iosBundleId: 'com.example.cardApp.RunnerTests',
  );
}
